development:
  adapter: postgresql
  encoding: utf8
  database: ducking_nemesis_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: ducking_nemesis_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: ducking_nemesis_production
  pool: 5
  username:
  password:
